### ISSUE TITLE
Fatal error with the last plugin

### ISSUE THREAD

**Issue by zekirma** [methnen/m-chart-highcharts-library#18]
I got this message

Fatal error: Cannot declare class M_Chart_Highcharts_Library, because the name is already in use in /home/xxx/www/wp-content/plugins/m-chart-highcharts-library/components/class-m-chart-highcharts-library.php on line 3

**Comment by methnen** [comment]
@zekirma thanks for the report.

Can you provide any more information on when this is happening to you? What is the situation that this occurs? Is there a way I can see this happening on your install?

**Comment by zekirma** [comment]
I found the solution; The version 1.04 was always active. I deleted this and activate the las one.

**Comment by methnen** [comment]
Ah. Glad you figured it out. A bit concerning it wasn't replaced by the latest version though. It should have if the name of the plugin directory was the same.
