### ISSUE TITLE
Consider adding Highcharts accessibility module

### ISSUE THREAD

**Issue by nkryptic** [methnen/m-chart-highcharts-library#24]
Highcharts provides an accessibility module that only requires the corresponding javascript file to be included along with the Highcharts library.  [This Highcharts page explains it](https://www.highcharts.com/docs/accessibility/accessibility-module).

If you'd be amenable, let me know and I can put together a pull request for you.

**Comment by methnen** [comment]
@nkryptic I'd have no problems with that at all. :)

**Comment by nkryptic** [comment]
ok, will do.  thanks.

**Comment by methnen** [comment]
Note that there's an existing PR and branch for 1.2.3, feel free to combine that change in there.

It'll go out when the latest M Chart settles down a bit feature wise and gets released.

**Comment by nkryptic** [comment]
ok. Hopefully, I can remember how to do that... I think that means I create my branch off of the 1.2.3 branch and then add my work and submit the PR? 

Btw, are you considering updating the Highcharts js?  You still have v9.1.0 from 2021-05-03 and the latest is v9.3.3 from 2022-02-01.

**Comment by methnen** [comment]
Yes, I almost always try to update Highcharts to whatever the latest is at the time of release. After some quick spot checks to make sure the update doesn't break anything of course.

**Comment by methnen** [comment]
And yes, you'd just pull the 1.2.3 branch and then submit your PR to that branch instead of master. And when I merge the change in it'll be included in the PR from 1.2.3 into master.

**Comment by nkryptic** [comment]
Closing this issue, as the PR has the relevant changes: #25
