### ISSUE TITLE
Make it so install order doesn't matter

### ISSUE THREAD

**Issue by imjeffp** [methnen/m-chart-highcharts-library#5]
After installing and activating, logging into wp-admin returns a screen with this:

Fatal error: Uncaught Error: Call to undefined function m_chart() in /home6/webberen/public_html/resourcefulness/wp-content/plugins/m-chart-highcharts-library/components/class-m-chart-highcharts-library.php:71 Stack trace: #0 /home6/webberen/public_html/resourcefulness/wp-includes/class-wp-hook.php(286): M_Chart_Highcharts_Library->current_screen(Object(WP_Screen)) #1 /home6/webberen/public_html/resourcefulness/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 /home6/webberen/public_html/resourcefulness/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /home6/webberen/public_html/resourcefulness/wp-admin/includes/class-wp-screen.php(376): do_action('current_screen', Object(WP_Screen)) #4 /home6/webberen/public_html/resourcefulness/wp-admin/includes/screen.php(232): WP_Screen->set_current_screen() #5 /home6/webberen/public_html/resourcefulness/wp-admin/admin.php(189): set_current_screen() #6 /home6/webberen/public_html/resourcefulness/wp-admin/index.php(10): require_once('/home6/webberen...') in /home6/webberen/public_html/resourcefulness/wp-content/plugins/m-chart-highcharts-library/components/class-m-chart-highcharts-library.php on line 71

**Comment by methnen** [comment]
Do you have M Chart installed as well? This plugin will not work without the other.

I should have a check in there that notifies users of that fact that though and prevents this. Thanks for catching that. Bone headed oversight on my part.

**Comment by imjeffp** [comment]
I would, but now I can't get to the install plug in page. Ack!

**Comment by methnen** [comment]
Can you login via FTP?

Change the name of the folder to: m-chart-highcharts-library_

**Comment by imjeffp** [comment]
FTP: Yes.

I'm sorry, but which folder? Path? (Not familiar with the directory structure of a WP site.)

**Comment by methnen** [comment]
You'll find it here: `wp-content -> plugins`

**Comment by imjeffp** [comment]
Ahhhh ... success. Renamed the directory (thanks for the path info), installed and activated M Chart, changed the directory name back, activated the library. Whew! Thanks for the rapid response!

Yeah, you might want a note about the order of activation. :-)

**Comment by methnen** [comment]
Good to hear it. Like I said totally bone headed of me that I didn't think of this situation. 

🤦‍♂️ 

Next version will correct that for sure.

**Comment by methnen** [comment]
Closing as the issue has been resolved in later versions.
